import React, { useState } from 'react';
import { 
  FileText, Calendar, ShieldCheck, Briefcase, DollarSign, 
  Files, ShieldAlert, Award, PhoneCall, Copy, Check, FileDown, 
  Trash2, Clock
} from 'lucide-react';
import { TimelineVisualizer } from './TimelineVisualizer.tsx';
import { GoNoGoScorecard } from './GoNoGoScorecard.tsx';
import { useNotification } from './NotificationProvider';

interface TenderDetailProps {
  tender: {
    id: string;
    name: string;
    status: 'Active' | 'Submitted' | 'Expired';
    deadline: string | null;
    file_size: number;
    page_count: number | null;
    analysis_result: any;
    extracted_text: string;
    created_at: string;
  };
  onDelete: (id: string) => void;
  onUpdateStatus: (id: string, status: 'Active' | 'Submitted' | 'Expired') => void;
}

export const TenderDetail: React.FC<TenderDetailProps> = ({ 
  tender, 
  onDelete, 
  onUpdateStatus 
}) => {
  const { showToast } = useNotification();
  const [activeTab, setActiveTab] = useState<'analysis' | 'timeline' | 'gonogo'>('analysis');
  const [copiedSection, setCopiedSection] = useState<string | null>(null);

  const sections = tender.analysis_result || {};

  // Card icons config
  const sectionConfig: Record<string, { title: string; icon: any }> = {
    executive_summary: { title: "Executive Summary", icon: FileText },
    eligibility_criteria: { title: "Eligibility Criteria", icon: ShieldCheck },
    key_dates: { title: "Key Dates & Deadlines", icon: Calendar },
    scope_of_work: { title: "Scope of Work", icon: Briefcase },
    financial_requirements: { title: "Financial Requirements", icon: DollarSign },
    required_documents: { title: "Required Documents Checklist", icon: Files },
    risks_penalties: { title: "Risks & Penalties", icon: ShieldAlert },
    evaluation_criteria: { title: "Evaluation Criteria", icon: Award },
    contact_details: { title: "Contact Details", icon: PhoneCall },
  };

  const copyToClipboard = (text: string, sectionKey: string) => {
    navigator.clipboard.writeText(text);
    setCopiedSection(sectionKey);
    setTimeout(() => setCopiedSection(null), 2000);
  };

  const handleCopyAll = () => {
    let fullTextReport = `TenderIQ Analysis Report: ${tender.name}\n`;
    fullTextReport += `Generated: ${new Date(tender.created_at).toLocaleDateString()}\n`;
    fullTextReport += `Deadline: ${tender.deadline ? new Date(tender.deadline).toLocaleString() : 'Not Found'}\n\n`;
    fullTextReport += `=========================================\n\n`;

    Object.entries(sectionConfig).forEach(([key, config]) => {
      const data = sections[key];
      if (data && data.found) {
        fullTextReport += `${config.title.toUpperCase()}\n`;
        if (key === 'financial_requirements') {
          fullTextReport += `EMD/Bid Security: ${data.emd || 'N/A'}\n`;
          fullTextReport += `Minimum Turnover: ${data.turnover || 'N/A'}\n`;
        }
        if (key === 'contact_details') {
          fullTextReport += `Authority: ${data.authority || 'N/A'}\n`;
          fullTextReport += `Email: ${data.email || 'N/A'}\n`;
          fullTextReport += `Phone: ${data.phone || 'N/A'}\n`;
          fullTextReport += `Portal: ${data.portal || 'N/A'}\n`;
        }
        const content = data.content || data.checklist || [];
        content.forEach((bullet: string) => {
          fullTextReport += `- ${bullet}\n`;
        });
        fullTextReport += `\n`;
      }
    });

    navigator.clipboard.writeText(fullTextReport);
    showToast("Full analysis report copied to clipboard!", "success");
  };

  const handleExportPDF = () => {
    // Basic browser printing setup for saving as PDF
    window.print();
  };

  const handleExportWord = () => {
    // Generate a standard clean HTML template representing the Word Doc
    let htmlContent = `
      <html xmlns:o='urn:schemas-microsoft-com:office:office' xmlns:w='urn:schemas-microsoft-com:office:word' xmlns='http://www.w3.org/TR/REC-html40'>
      <head>
        <title>TenderIQ Report - ${tender.name}</title>
        <style>
          body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; }
          h1 { color: #1e3a8a; border-bottom: 2px solid #1e3a8a; padding-bottom: 8px; }
          h2 { color: #0f766e; margin-top: 24px; border-bottom: 1px solid #ddd; padding-bottom: 4px; }
          ul { padding-left: 20px; }
          li { margin-bottom: 6px; }
          .meta { font-style: italic; color: #555; margin-bottom: 20px; }
        </style>
      </head>
      <body>
        <h1>Tender Analysis Report: ${tender.name}</h1>
        <div class="meta">
          <p><strong>Generated by:</strong> TenderIQ Procurement Portal</p>
          <p><strong>Date:</strong> ${new Date().toLocaleDateString()}</p>
          <p><strong>Tender Deadline:</strong> ${tender.deadline ? new Date(tender.deadline).toLocaleString() : 'Not Found'}</p>
        </div>
    `;

    Object.entries(sectionConfig).forEach(([key, config]) => {
      const data = sections[key];
      if (data && data.found) {
        htmlContent += `<h2>${config.title}</h2>`;
        if (key === 'financial_requirements') {
          htmlContent += `<p><strong>EMD / Bid Security:</strong> ${data.emd || 'Not Found'}</p>`;
          htmlContent += `<p><strong>Minimum Turnover Required:</strong> ${data.turnover || 'Not Found'}</p>`;
        }
        if (key === 'contact_details') {
          htmlContent += `<p><strong>Issuing Authority:</strong> ${data.authority || 'N/A'}</p>`;
          htmlContent += `<p><strong>Contact Email:</strong> ${data.email || 'N/A'}</p>`;
          htmlContent += `<p><strong>Contact Phone:</strong> ${data.phone || 'N/A'}</p>`;
          htmlContent += `<p><strong>Tender Portal:</strong> ${data.portal || 'N/A'}</p>`;
        }
        
        const listItems = data.content || data.checklist || [];
        if (listItems.length > 0) {
          htmlContent += `<ul>`;
          listItems.forEach((bullet: string) => {
            htmlContent += `<li>${bullet}</li>`;
          });
          htmlContent += `</ul>`;
        } else {
          htmlContent += `<p>No bullet items extracted.</p>`;
        }
      }
    });

    htmlContent += `</body></html>`;

    const blob = new Blob(['\ufeff' + htmlContent], {
      type: 'application/msword'
    });
    
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${tender.name.replace(/\.[^/.]+$/, "")}_TenderIQ_Analysis.doc`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const getDaysRemaining = () => {
    if (!tender.deadline) return null;
    const diff = new Date(tender.deadline).getTime() - new Date().getTime();
    const days = Math.ceil(diff / (1000 * 60 * 60 * 24));
    return days;
  };

  const daysLeft = getDaysRemaining();

  return (
    <div className="analysis-panel printable-area">
      {/* Tender Header */}
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', flexWrap: 'wrap', gap: '16px' }} className="non-printable">
        <div>
          <h1 style={{ fontSize: '24px', marginBottom: '8px' }}>{tender.name}</h1>
          <div style={{ display: 'flex', alignItems: 'center', gap: '12px', flexWrap: 'wrap' }}>
            <span style={{ fontSize: '13px', color: 'var(--text-secondary)' }}>
              Pages: <strong style={{ color: '#ffffff' }}>{tender.page_count || 'N/A'}</strong>
            </span>
            <span style={{ width: '4px', height: '4px', borderRadius: '50%', backgroundColor: 'var(--border-color)' }}></span>
            <span style={{ fontSize: '13px', color: 'var(--text-secondary)' }}>
              Uploaded: <strong style={{ color: '#ffffff' }}>{new Date(tender.created_at).toLocaleDateString()}</strong>
            </span>
            <span style={{ width: '4px', height: '4px', borderRadius: '50%', backgroundColor: 'var(--border-color)' }}></span>
            <div style={{ display: 'flex', alignItems: 'center', gap: '6px' }}>
              <span style={{ fontSize: '13px', color: 'var(--text-secondary)' }}>Status:</span>
              <select
                value={tender.status}
                onChange={(e) => onUpdateStatus(tender.id, e.target.value as any)}
                style={{
                  background: 'var(--bg-secondary)',
                  border: '1px solid var(--border-color)',
                  color: '#ffffff',
                  fontSize: '12px',
                  fontWeight: '600',
                  padding: '2px 8px',
                  borderRadius: '4px',
                  outline: 'none',
                  cursor: 'pointer'
                }}
              >
                <option value="Active">Active</option>
                <option value="Submitted">Submitted</option>
                <option value="Expired">Expired</option>
              </select>
            </div>
          </div>
        </div>

        <div style={{ display: 'flex', gap: '10px' }}>
          {daysLeft !== null && (
            <div className={`countdown-box ${daysLeft <= 0 ? 'expired' : ''}`}>
              <Clock size={16} />
              {daysLeft > 0 ? (
                <span>{daysLeft} days remaining</span>
              ) : daysLeft === 0 ? (
                <span>Deadline Today</span>
              ) : (
                <span>Deadline Passed</span>
              )}
            </div>
          )}

          <button className="btn" onClick={handleCopyAll}>
            <Copy size={14} /> Copy All
          </button>
          <button className="btn" onClick={handleExportPDF}>
            <FileDown size={14} /> Export PDF
          </button>
          <button className="btn" onClick={handleExportWord}>
            <FileDown size={14} /> Export Word
          </button>
          <button className="btn btn-danger" onClick={() => onDelete(tender.id)}>
            <Trash2 size={14} />
          </button>
        </div>
      </div>

      {/* Tabs */}
      <div className="view-tabs non-printable">
        <button 
          className={`tab-btn ${activeTab === 'analysis' ? 'active' : ''}`}
          onClick={() => setActiveTab('analysis')}
        >
          Analysis Report
        </button>
        <button 
          className={`tab-btn ${activeTab === 'timeline' ? 'active' : ''}`}
          onClick={() => setActiveTab('timeline')}
        >
          Timeline Visualizer
        </button>
        <button 
          className={`tab-btn ${activeTab === 'gonogo' ? 'active' : ''}`}
          onClick={() => setActiveTab('gonogo')}
        >
          Bid Go-NoGo Scorecard
        </button>
      </div>

      {/* Main Tab Render */}
      {activeTab === 'analysis' && (
        <div className="cards-grid">
          {Object.entries(sectionConfig).map(([key, config]) => {
            const Icon = config.icon;
            const data = sections[key];
            const found = data?.found !== false;
            
            // Format bullet contents or descriptions
            const bullets = data?.content || data?.checklist || [];

            return (
              <div 
                key={key} 
                className={`analysis-card ${!found ? 'not-found' : ''}`}
              >
                <div className="card-header">
                  <div className="card-title-group">
                    <Icon size={18} className="card-icon" />
                    <span className="card-title">{config.title}</span>
                  </div>
                </div>

                <div className="card-body">
                  {!found ? (
                    <p style={{ fontStyle: 'italic', color: 'var(--text-muted)' }}>
                      Information not found in document
                    </p>
                  ) : (
                    <>
                      {/* Section-specific detailed fields */}
                      {key === 'financial_requirements' && (
                        <div style={{ 
                          background: 'var(--bg-secondary)', 
                          padding: '10px', 
                          borderRadius: '6px', 
                          marginBottom: '12px',
                          border: '1px solid var(--border-light)',
                          fontSize: '12px',
                          display: 'flex',
                          flexDirection: 'column',
                          gap: '4px'
                        }}>
                          <div>EMD / Bid Security: <strong style={{ color: 'var(--primary)' }}>{data.emd || 'N/A'}</strong></div>
                          <div>Min Annual Turnover: <strong style={{ color: 'var(--secondary)' }}>{data.turnover || 'N/A'}</strong></div>
                        </div>
                      )}

                      {key === 'contact_details' && (
                        <div style={{ 
                          background: 'var(--bg-secondary)', 
                          padding: '10px', 
                          borderRadius: '6px', 
                          marginBottom: '12px',
                          border: '1px solid var(--border-light)',
                          fontSize: '12px',
                          display: 'flex',
                          flexDirection: 'column',
                          gap: '4px'
                        }}>
                          <div>Authority: <strong>{data.authority || 'N/A'}</strong></div>
                          {data.email && <div>Email: <a href={`mailto:${data.email}`} style={{ color: 'var(--secondary)', textDecoration: 'none' }}>{data.email}</a></div>}
                          {data.phone && <div>Phone: <strong>{data.phone}</strong></div>}
                          {data.portal && <div>Portal: <a href={data.portal} target="_blank" rel="noopener noreferrer" style={{ color: 'var(--primary)', textDecoration: 'none' }}>Link</a></div>}
                        </div>
                      )}

                      {bullets.length > 0 ? (
                        <ul>
                          {bullets.map((bullet: string, idx: number) => (
                            <li key={idx}>{bullet}</li>
                          ))}
                        </ul>
                      ) : (
                        <p>{data?.description || 'Data extracted.'}</p>
                      )}
                    </>
                  )}
                </div>

                {found && bullets.length > 0 && (
                  <div className="card-footer non-printable">
                    <button 
                      className="card-copy-btn"
                      onClick={() => {
                        const copyText = bullets.map((b: string) => `- ${b}`).join('\n');
                        copyToClipboard(copyText, key);
                      }}
                    >
                      {copiedSection === key ? (
                        <>
                          <Check size={12} /> Copied!
                        </>
                      ) : (
                        <>
                          <Copy size={12} /> Copy Section
                        </>
                      )}
                    </button>
                  </div>
                )}
              </div>
            );
          })}
        </div>
      )}

      {activeTab === 'timeline' && (
        <TimelineVisualizer timelineData={sections.key_dates?.timeline || []} additionalInfo={sections.key_dates?.content || []} />
      )}

      {activeTab === 'gonogo' && (
        <GoNoGoScorecard tender={tender} />
      )}

      {/* Special styles to handle print PDF rendering beautifully */}
      <style>{`
        @media print {
          body {
            background-color: white !important;
            color: black !important;
          }
          .printable-area {
            position: absolute;
            left: 0;
            top: 0;
            width: 100% !important;
            padding: 0 !important;
            background: white !important;
            color: black !important;
          }
          .non-printable {
            display: none !important;
          }
          .cards-grid {
            display: block !important;
          }
          .analysis-card {
            page-break-inside: avoid;
            background: white !important;
            border: 1px solid #ccc !important;
            color: black !important;
            box-shadow: none !important;
            margin-bottom: 24px;
            opacity: 1 !important;
          }
          h1, h2, h3, .card-title {
            color: black !important;
          }
          .card-icon {
            color: #333 !important;
          }
          .countdown-box {
            display: none !important;
          }
        }
      `}</style>
    </div>
  );
};
